---

- name: Создать пользователя maxim
  postgresql_user:
    name: maxim
    password: "maxim"
    role_attr_flags: SUPERUSER
  environment:
    PGOPTIONS: "-c password_encryption=md5"

- name: Отозвать привилегии роли public в схеме public
  postgresql_privs:
    db: template1
    state: absent
    privs: CREATE
    objs: ALL_IN_SCHEMA
    role: PUBLIC

- name: Создать сервисную УЗ для 1c
  postgresql_user:
    name: svc_1c
    password: "svc_1c"
    role_attr_flags: LOGIN,CREATEDB
  environment:
    PGOPTIONS: "-c password_encryption=md5"

- name: Гранты для сервисной УЗ 1c
  postgresql_membership:
    group: "{{  item.group  }}"
    target_role: svc_1c
    state: present
  loop:
    - { pg_read_all_data  }
    - { pg_write_all_data  }
    - { pg_read_all_settings  }
    - { pg_read_all_stats  }
    - { pg_stat_scan_tables  }
    - { pg_monitor  }
    - { pg_signal_backend  }
